import {
  Award, Banknote, BarChart3, Bell, BookMarked, BookOpen, Bot, Briefcase, Bus,
  Calendar, CalendarClock, CalendarOff, Circle, CircleDollarSign, ClipboardCheck,
  ClipboardList, Contact, CreditCard, FileBadge, FileInput, FileText, FolderOpen,
  GraduationCap, HelpCircle, History, Home, IdCard, Image, Images, Layers,
  LayoutDashboard, Library, Link, ListChecks, MapPinned, Megaphone, MessageCircle,
  MonitorPlay, Package, Palette, PenLine, PieChart, Radio, Receipt, Route, School,
  ScrollText, Settings, Shield, Sparkles, Stamp, Star, UserCheck, UserCog, Users,
  UsersRound, Wallet, Tv,
} from 'lucide-react';

/** Lucide icon name → component (sidebar-safe icons only). */
export const MENU_ICON_MAP = {
  Home,
  LayoutDashboard,
  FileText,
  FileInput,
  FileBadge,
  GraduationCap,
  CreditCard,
  CircleDollarSign,
  Image,
  Images,
  MessageCircle,
  Bell,
  BarChart3,
  PieChart,
  Settings,
  Shield,
  Palette,
  FolderOpen,
  Users,
  UsersRound,
  UserCog,
  UserCheck,
  Contact,
  HelpCircle,
  Link,
  BookOpen,
  BookMarked,
  Library,
  Calendar,
  CalendarClock,
  CalendarOff,
  Star,
  ClipboardList,
  ClipboardCheck,
  Megaphone,
  Tv,
  Bus,
  Route,
  MapPinned,
  IdCard,
  ListChecks,
  Package,
  Briefcase,
  Banknote,
  Wallet,
  Receipt,
  Award,
  Bot,
  Sparkles,
  Stamp,
  MonitorPlay,
  PenLine,
  Radio,
  History,
  ScrollText,
  School,
  Layers,
  Circle,
};

export const MENU_ICON_OPTIONS = Object.keys(MENU_ICON_MAP).map((value) => ({
  value,
  label: value.replace(/([A-Z])/g, ' $1').trim(),
}));

/** @param {string | undefined} iconName @param {import('react').ComponentType | undefined} fallback */
export function resolveMenuIcon(iconName, fallback) {
  if (iconName && MENU_ICON_MAP[iconName]) return MENU_ICON_MAP[iconName];
  return fallback || Circle;
}
