import { ROLES } from './roles.js';

export const PERMISSIONS = {
  // Applications
  VIEW_APPLICATIONS: 'view_applications',
  EDIT_APPLICATIONS: 'edit_applications',
  APPROVE_APPLICATIONS: 'approve_applications',
  REJECT_APPLICATIONS: 'reject_applications',
  REQUEST_CORRECTION: 'request_correction',
  VERIFY_DOCUMENTS: 'verify_documents',
  REJECT_DOCUMENTS: 'reject_documents',

  // Fees
  VIEW_FEES: 'view_fees',
  ASSIGN_FEES: 'assign_fees',
  VERIFY_PAYMENTS: 'verify_payments',
  REJECT_PAYMENTS: 'reject_payments',
  GENERATE_RECEIPTS: 'generate_receipts',

  // Accounts
  CREATE_ACCOUNTS: 'create_accounts',
  MANAGE_USERS: 'manage_users',
  MANAGE_ROLES: 'manage_roles',

  // Media & Chat
  SEND_PHOTOS: 'send_photos',
  MODERATE_PHOTOS: 'moderate_photos',
  SEND_MESSAGES: 'send_messages',
  VIEW_ALL_CHAT: 'view_all_chat',

  // School
  MANAGE_SCHOOLS: 'manage_schools',
  MANAGE_PORTAL_SETTINGS: 'manage_portal_settings',
  MANAGE_SETTINGS: 'manage_settings',
  VIEW_REPORTS: 'view_reports',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  CONFIRM_ADMISSION: 'confirm_admission',
};

/** @type {Record<string, string[]>} */
export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.VIEW_APPLICATIONS, PERMISSIONS.EDIT_APPLICATIONS,
    PERMISSIONS.APPROVE_APPLICATIONS, PERMISSIONS.REJECT_APPLICATIONS,
    PERMISSIONS.REQUEST_CORRECTION, PERMISSIONS.VERIFY_DOCUMENTS,
    PERMISSIONS.REJECT_DOCUMENTS, PERMISSIONS.VIEW_FEES, PERMISSIONS.ASSIGN_FEES,
    PERMISSIONS.VERIFY_PAYMENTS, PERMISSIONS.REJECT_PAYMENTS, PERMISSIONS.GENERATE_RECEIPTS,
    PERMISSIONS.CREATE_ACCOUNTS, PERMISSIONS.MANAGE_USERS, PERMISSIONS.SEND_PHOTOS,
    PERMISSIONS.MODERATE_PHOTOS, PERMISSIONS.SEND_MESSAGES, PERMISSIONS.VIEW_ALL_CHAT,
    PERMISSIONS.MANAGE_SETTINGS, PERMISSIONS.MANAGE_PORTAL_SETTINGS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.CONFIRM_ADMISSION,
  ],

  [ROLES.ADMISSION_OFFICER]: [
    PERMISSIONS.VIEW_APPLICATIONS, PERMISSIONS.EDIT_APPLICATIONS,
    PERMISSIONS.REQUEST_CORRECTION, PERMISSIONS.VERIFY_DOCUMENTS,
    PERMISSIONS.REJECT_DOCUMENTS, PERMISSIONS.APPROVE_APPLICATIONS,
    PERMISSIONS.VIEW_FEES, PERMISSIONS.ASSIGN_FEES,
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.VIEW_FEES, PERMISSIONS.ASSIGN_FEES,
    PERMISSIONS.VERIFY_PAYMENTS, PERMISSIONS.REJECT_PAYMENTS,
    PERMISSIONS.GENERATE_RECEIPTS, PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.TEACHER]: [
    PERMISSIONS.SEND_PHOTOS, PERMISSIONS.SEND_MESSAGES,
  ],

  [ROLES.PARENT]: [
    PERMISSIONS.VIEW_APPLICATIONS, PERMISSIONS.EDIT_APPLICATIONS,
    PERMISSIONS.VIEW_FEES, PERMISSIONS.SEND_MESSAGES,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.SEND_MESSAGES,
  ],

  [ROLES.SUPPORT_STAFF]: [
    PERMISSIONS.SEND_MESSAGES, PERMISSIONS.VIEW_ALL_CHAT,
  ],
};

export function hasPermission(role, permission) {
  const perms = ROLE_PERMISSIONS[role] || [];
  return perms.includes(permission);
}

export function canAccessApplication(role, userId, application) {
  if ([ROLES.SUPER_ADMIN, ROLES.SCHOOL_ADMIN, ROLES.ADMISSION_OFFICER].includes(role)) return true;
  if (role === ROLES.PARENT) return application.parentId === userId;
  return false;
}
